/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.restful.restControllerGeneration;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Method With</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sdu.mdsd.restful.restControllerGeneration.CreateMethodWith#getEntity <em>Entity</em>}</li>
 *   <li>{@link sdu.mdsd.restful.restControllerGeneration.CreateMethodWith#getEntityId <em>Entity Id</em>}</li>
 * </ul>
 *
 * @see sdu.mdsd.restful.restControllerGeneration.RestControllerGenerationPackage#getCreateMethodWith()
 * @model
 * @generated
 */
public interface CreateMethodWith extends EObject
{
  /**
   * Returns the value of the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' reference.
   * @see #setEntity(Entity)
   * @see sdu.mdsd.restful.restControllerGeneration.RestControllerGenerationPackage#getCreateMethodWith_Entity()
   * @model
   * @generated
   */
  Entity getEntity();

  /**
   * Sets the value of the '{@link sdu.mdsd.restful.restControllerGeneration.CreateMethodWith#getEntity <em>Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(Entity value);

  /**
   * Returns the value of the '<em><b>Entity Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Id</em>' reference.
   * @see #setEntityId(Attribute)
   * @see sdu.mdsd.restful.restControllerGeneration.RestControllerGenerationPackage#getCreateMethodWith_EntityId()
   * @model
   * @generated
   */
  Attribute getEntityId();

  /**
   * Sets the value of the '{@link sdu.mdsd.restful.restControllerGeneration.CreateMethodWith#getEntityId <em>Entity Id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity Id</em>' reference.
   * @see #getEntityId()
   * @generated
   */
  void setEntityId(Attribute value);

} // CreateMethodWith
