/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.restful.restControllerGeneration;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sdu.mdsd.restful.restControllerGeneration.RestControllerGenerationPackage#getEntityDeclaration()
 * @model
 * @generated
 */
public interface EntityDeclaration extends EObject
{
} // EntityDeclaration
