/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.restful.restControllerGeneration;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sdu.mdsd.restful.restControllerGeneration.Entity#getBase <em>Base</em>}</li>
 *   <li>{@link sdu.mdsd.restful.restControllerGeneration.Entity#getDeclarations <em>Declarations</em>}</li>
 * </ul>
 *
 * @see sdu.mdsd.restful.restControllerGeneration.RestControllerGenerationPackage#getEntity()
 * @model
 * @generated
 */
public interface Entity extends Declaration
{
  /**
   * Returns the value of the '<em><b>Base</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base</em>' reference.
   * @see #setBase(Entity)
   * @see sdu.mdsd.restful.restControllerGeneration.RestControllerGenerationPackage#getEntity_Base()
   * @model
   * @generated
   */
  Entity getBase();

  /**
   * Sets the value of the '{@link sdu.mdsd.restful.restControllerGeneration.Entity#getBase <em>Base</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base</em>' reference.
   * @see #getBase()
   * @generated
   */
  void setBase(Entity value);

  /**
   * Returns the value of the '<em><b>Declarations</b></em>' containment reference list.
   * The list contents are of type {@link sdu.mdsd.restful.restControllerGeneration.EntityDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declarations</em>' containment reference list.
   * @see sdu.mdsd.restful.restControllerGeneration.RestControllerGenerationPackage#getEntity_Declarations()
   * @model containment="true"
   * @generated
   */
  EList<EntityDeclaration> getDeclarations();

} // Entity
