/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.restful.restControllerGeneration;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Method</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sdu.mdsd.restful.restControllerGeneration.RestControllerGenerationPackage#getListMethod()
 * @model
 * @generated
 */
public interface ListMethod extends MethodType
{
} // ListMethod
