/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.restful.restControllerGeneration;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sdu.mdsd.restful.restControllerGeneration.RestControllerGenerationPackage#getMethodType()
 * @model
 * @generated
 */
public interface MethodType extends MethodDef
{
} // MethodType
