/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.restful.restControllerGeneration;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sdu.mdsd.restful.restControllerGeneration.Name#getVarName <em>Var Name</em>}</li>
 * </ul>
 *
 * @see sdu.mdsd.restful.restControllerGeneration.RestControllerGenerationPackage#getName_()
 * @model
 * @generated
 */
public interface Name extends Expression
{
  /**
   * Returns the value of the '<em><b>Var Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Name</em>' reference.
   * @see #setVarName(Attribute)
   * @see sdu.mdsd.restful.restControllerGeneration.RestControllerGenerationPackage#getName_VarName()
   * @model
   * @generated
   */
  Attribute getVarName();

  /**
   * Sets the value of the '{@link sdu.mdsd.restful.restControllerGeneration.Name#getVarName <em>Var Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Name</em>' reference.
   * @see #getVarName()
   * @generated
   */
  void setVarName(Attribute value);

} // Name
