/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.restful.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class RestControllerGenerationDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
