/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.restful.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RestControllerGenerationUiModule extends AbstractRestControllerGenerationUiModule {

	public RestControllerGenerationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
