/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.restful.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import sdu.mdsd.restful.RestControllerGenerationRuntimeModule;
import sdu.mdsd.restful.RestControllerGenerationStandaloneSetup;
import sdu.mdsd.restful.ide.RestControllerGenerationIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RestControllerGenerationIdeSetup extends RestControllerGenerationStandaloneSetup {
  @Override
  public Injector createInjector() {
    RestControllerGenerationRuntimeModule _restControllerGenerationRuntimeModule = new RestControllerGenerationRuntimeModule();
    RestControllerGenerationIdeModule _restControllerGenerationIdeModule = new RestControllerGenerationIdeModule();
    return Guice.createInjector(Modules2.mixin(_restControllerGenerationRuntimeModule, _restControllerGenerationIdeModule));
  }
}
