/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.restful.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sdu.mdsd.restful.parser.antlr.internal.InternalRestControllerGenerationParser;
import sdu.mdsd.restful.services.RestControllerGenerationGrammarAccess;

public class RestControllerGenerationParser extends AbstractAntlrParser {

	@Inject
	private RestControllerGenerationGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRestControllerGenerationParser createParser(XtextTokenStream stream) {
		return new InternalRestControllerGenerationParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "EntityModel";
	}

	public RestControllerGenerationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RestControllerGenerationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
