/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.restful.generator;

import com.google.common.collect.Iterables;
import com.google.common.collect.Iterators;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.function.Consumer;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import sdu.mdsd.restful.restControllerGeneration.Add;
import sdu.mdsd.restful.restControllerGeneration.Attribute;
import sdu.mdsd.restful.restControllerGeneration.Comparison;
import sdu.mdsd.restful.restControllerGeneration.Conjunction;
import sdu.mdsd.restful.restControllerGeneration.Controller;
import sdu.mdsd.restful.restControllerGeneration.ControllerMethod;
import sdu.mdsd.restful.restControllerGeneration.CreateMethod;
import sdu.mdsd.restful.restControllerGeneration.DeleteMethod;
import sdu.mdsd.restful.restControllerGeneration.Disjunction;
import sdu.mdsd.restful.restControllerGeneration.Div;
import sdu.mdsd.restful.restControllerGeneration.Entity;
import sdu.mdsd.restful.restControllerGeneration.EntityModel;
import sdu.mdsd.restful.restControllerGeneration.Expression;
import sdu.mdsd.restful.restControllerGeneration.ExternalDef;
import sdu.mdsd.restful.restControllerGeneration.ExternalUse;
import sdu.mdsd.restful.restControllerGeneration.ExternalUseOfAttribute;
import sdu.mdsd.restful.restControllerGeneration.GetMethod;
import sdu.mdsd.restful.restControllerGeneration.IntExp;
import sdu.mdsd.restful.restControllerGeneration.ListMethod;
import sdu.mdsd.restful.restControllerGeneration.LogicRequirement;
import sdu.mdsd.restful.restControllerGeneration.Mul;
import sdu.mdsd.restful.restControllerGeneration.Name;
import sdu.mdsd.restful.restControllerGeneration.Proposition;
import sdu.mdsd.restful.restControllerGeneration.RelEQ;
import sdu.mdsd.restful.restControllerGeneration.RelGT;
import sdu.mdsd.restful.restControllerGeneration.RelGTE;
import sdu.mdsd.restful.restControllerGeneration.RelLT;
import sdu.mdsd.restful.restControllerGeneration.RelLTE;
import sdu.mdsd.restful.restControllerGeneration.RelationalOp;
import sdu.mdsd.restful.restControllerGeneration.Requirement;
import sdu.mdsd.restful.restControllerGeneration.Sub;
import sdu.mdsd.restful.restControllerGeneration.UpdateMethod;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class RestControllerGenerationGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final EntityModel em = Iterators.<EntityModel>filter(resource.getAllContents(), EntityModel.class).next();
    System.out.println("Model:");
    this.display(em);
    this.generateExternalInterface(em, fsa);
    this.generateModelFiles(em, fsa);
    this.generateControllerFiles(em, fsa);
    this.generateEntityApplicationInterfaces(em, fsa);
  }
  
  public void display(final EObject model) {
    try {
      final XMLResourceImpl res = new XMLResourceImpl();
      res.getContents().add(EcoreUtil.<EObject>copy(model));
      System.out.println("Dump of model:");
      res.save(System.out, null);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  public void generateModelFiles(final EntityModel model, final IFileSystemAccess2 fsa) {
    final Consumer<Entity> _function = (Entity it) -> {
      this.generateEntity(it, fsa);
    };
    Iterables.<Entity>filter(model.getDeclarations(), Entity.class).forEach(_function);
  }
  
  public void generateEntity(final Entity entity, final IFileSystemAccess2 fsa) {
    final EntityModel model = EcoreUtil2.<EntityModel>getContainerOfType(entity, EntityModel.class);
    String _name = model.getName();
    String _plus = (_name + "/Models/");
    String _name_1 = entity.getName();
    String _plus_1 = (_plus + _name_1);
    String _plus_2 = (_plus_1 + ".cs");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("using System;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("namespace ");
    String _name_2 = model.getName();
    _builder.append(_name_2);
    _builder.append(".Models {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("public class ");
    String _name_3 = entity.getName();
    _builder.append(_name_3, "\t");
    _builder.append(" ");
    {
      Entity _base = entity.getBase();
      boolean _tripleNotEquals = (_base != null);
      if (_tripleNotEquals) {
        _builder.append(": ");
        String _name_4 = entity.getBase().getName();
        _builder.append(_name_4, "\t");
        _builder.append(" ");
      }
    }
    _builder.append("{");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    CharSequence _generateConstructor = this.generateConstructor(entity);
    _builder.append(_generateConstructor, "\t\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    CharSequence _generateAttributes = this.generateAttributes(entity);
    _builder.append(_generateAttributes, "\t\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    CharSequence _generateAttributeRequirements = this.generateAttributeRequirements(entity);
    _builder.append(_generateAttributeRequirements, "\t\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    fsa.generateFile(_plus_2, _builder);
  }
  
  public CharSequence generateAttributes(final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    {
      Entity _base = entity.getBase();
      boolean _tripleEquals = (_base == null);
      if (_tripleEquals) {
        _builder.append("protected readonly IExternalCode ExternalCode;");
        _builder.newLine();
      }
    }
    {
      Iterable<Attribute> _filter = Iterables.<Attribute>filter(entity.getDeclarations(), Attribute.class);
      for(final Attribute x : _filter) {
        CharSequence _generateAttribute = this.generateAttribute(x);
        _builder.append(_generateAttribute);
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder;
  }
  
  public CharSequence generateAttribute(final Attribute attribute) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public ");
    String _name = attribute.getType().getName();
    _builder.append(_name);
    _builder.append(" ");
    String _name_1 = attribute.getName();
    _builder.append(_name_1);
    _builder.append(" { get; }");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public CharSequence generateConstructor(final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public ");
    String _name = entity.getName();
    _builder.append(_name);
    _builder.append("(");
    CharSequence _generateConstructorParameters = this.generateConstructorParameters(entity);
    _builder.append(_generateConstructorParameters);
    _builder.append(") ");
    {
      Entity _base = entity.getBase();
      boolean _tripleNotEquals = (_base != null);
      if (_tripleNotEquals) {
        _builder.append(": base(");
        CharSequence _generateConstructorParametersWithoutType = this.generateConstructorParametersWithoutType(entity.getBase());
        _builder.append(_generateConstructorParametersWithoutType);
        _builder.append(") ");
      }
    }
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    {
      Entity _base_1 = entity.getBase();
      boolean _tripleEquals = (_base_1 == null);
      if (_tripleEquals) {
        _builder.append("\t");
        _builder.append("ExternalCode = externalCode;");
        _builder.newLine();
      }
    }
    {
      Iterable<Attribute> _filter = Iterables.<Attribute>filter(entity.getDeclarations(), Attribute.class);
      for(final Attribute x : _filter) {
        _builder.append("\t");
        CharSequence _generateConstructorSet = this.generateConstructorSet(x);
        _builder.append(_generateConstructorSet, "\t");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t");
    _builder.append("CheckRequirements();");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateConstructorParameters(final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _externCodeCtorParameter = this.externCodeCtorParameter(entity);
    _builder.append(_externCodeCtorParameter);
    {
      ArrayList<Attribute> _allAttributes = this.getAllAttributes(entity);
      boolean _hasElements = false;
      for(final Attribute x : _allAttributes) {
        if (!_hasElements) {
          _hasElements = true;
        } else {
          _builder.appendImmediate(", ", "");
        }
        CharSequence _generateConstructorParameter = this.generateConstructorParameter(x);
        _builder.append(_generateConstructorParameter);
      }
    }
    return _builder;
  }
  
  public CharSequence generateConstructorParametersWithoutType(final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _externCodeCtorParameterWithoutType = this.externCodeCtorParameterWithoutType(entity);
    _builder.append(_externCodeCtorParameterWithoutType);
    {
      ArrayList<Attribute> _allAttributes = this.getAllAttributes(entity);
      boolean _hasElements = false;
      for(final Attribute x : _allAttributes) {
        if (!_hasElements) {
          _hasElements = true;
        } else {
          _builder.appendImmediate(", ", "");
        }
        CharSequence _generateConstructorParameterWithoutType = this.generateConstructorParameterWithoutType(x);
        _builder.append(_generateConstructorParameterWithoutType);
      }
    }
    return _builder;
  }
  
  public CharSequence externCodeCtorParameter(final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("IExternalCode externalCode");
    {
      int _size = this.getAllAttributes(entity).size();
      boolean _greaterThan = (_size > 0);
      if (_greaterThan) {
        _builder.append(", ");
      }
    }
    return _builder;
  }
  
  public CharSequence externCodeCtorParameterWithoutType(final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("externalCode");
    {
      int _size = this.getAllAttributes(entity).size();
      boolean _greaterThan = (_size > 0);
      if (_greaterThan) {
        _builder.append(", ");
      }
    }
    return _builder;
  }
  
  public CharSequence generateConstructorParameter(final Attribute attribute) {
    StringConcatenation _builder = new StringConcatenation();
    String _name = attribute.getType().getName();
    _builder.append(_name);
    _builder.append(" ");
    String _firstLower = StringExtensions.toFirstLower(attribute.getName());
    _builder.append(_firstLower);
    return _builder;
  }
  
  public CharSequence generateConstructorParameterWithoutType(final Attribute attribute) {
    StringConcatenation _builder = new StringConcatenation();
    String _firstLower = StringExtensions.toFirstLower(attribute.getName());
    _builder.append(_firstLower);
    return _builder;
  }
  
  public CharSequence generateConstructorSet(final Attribute attribute) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("this.");
    String _name = attribute.getName();
    _builder.append(_name);
    _builder.append(" = ");
    String _firstLower = StringExtensions.toFirstLower(attribute.getName());
    _builder.append(_firstLower);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public CharSequence generateAttributeRequirements(final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public void CheckRequirements() {");
    _builder.newLine();
    {
      final Function1<Attribute, Boolean> _function = (Attribute a) -> {
        EObject _requires = a.getRequires();
        return Boolean.valueOf((_requires != null));
      };
      Iterable<Attribute> _filter = IterableExtensions.<Attribute>filter(Iterables.<Attribute>filter(entity.getDeclarations(), Attribute.class), _function);
      for(final Attribute x : _filter) {
        _builder.append("\t");
        _builder.append("if(!(");
        CharSequence _generateAttributeRequirement = this.generateAttributeRequirement(x.getRequires(), x);
        _builder.append(_generateAttributeRequirement, "\t");
        _builder.append(")) throw new Exception(\"Requirement not fulfilled\");");
        _builder.newLineIfNotEmpty();
      }
    }
    {
      Iterable<Requirement> _filter_1 = Iterables.<Requirement>filter(entity.getDeclarations(), Requirement.class);
      for(final Requirement x_1 : _filter_1) {
        _builder.append("\t");
        _builder.append("if(!(");
        CharSequence _generateRequirement = this.generateRequirement(x_1.getRequirement());
        _builder.append(_generateRequirement, "\t");
        _builder.append(")) throw new Exception(\"Requirement not fulfilled\");");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _generateAttributeRequirement(final ExternalUse requirement, final Attribute attribute) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("ExternalCode.");
    String _name = requirement.getExternal().getName();
    _builder.append(_name);
    _builder.append("(");
    String _name_1 = attribute.getName();
    _builder.append(_name_1);
    _builder.append(")");
    return _builder;
  }
  
  protected CharSequence _generateAttributeRequirement(final LogicRequirement requirement, final Attribute attribute) {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _generateLogic = this.generateLogic(requirement.getLogic());
    _builder.append(_generateLogic);
    return _builder;
  }
  
  protected CharSequence _generateRequirement(final LogicRequirement requirement) {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _generateLogic = this.generateLogic(requirement.getLogic());
    _builder.append(_generateLogic);
    return _builder;
  }
  
  protected CharSequence _generateRequirement(final ExternalUseOfAttribute requirement) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("ExternalCode.");
    String _name = requirement.getExternal().getName();
    _builder.append(_name);
    _builder.append("(");
    String _name_1 = requirement.getAttribute().getName();
    _builder.append(_name_1);
    _builder.append(")");
    return _builder;
  }
  
  protected CharSequence _generateLogic(final Disjunction x) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("(");
    CharSequence _generateLogic = this.generateLogic(x.getLeft());
    _builder.append(_generateLogic);
    _builder.append("||");
    CharSequence _generateLogic_1 = this.generateLogic(x.getRight());
    _builder.append(_generateLogic_1);
    _builder.append(")");
    return _builder;
  }
  
  protected CharSequence _generateLogic(final Conjunction x) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("(");
    CharSequence _generateLogic = this.generateLogic(x.getLeft());
    _builder.append(_generateLogic);
    _builder.append("&&");
    CharSequence _generateLogic_1 = this.generateLogic(x.getRight());
    _builder.append(_generateLogic_1);
    _builder.append(")");
    return _builder;
  }
  
  protected CharSequence _generateLogic(final Comparison x) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("(");
    CharSequence _generateExp = this.generateExp(x.getLeft());
    _builder.append(_generateExp);
    String _generateOp = this.generateOp(x.getOp());
    _builder.append(_generateOp);
    CharSequence _generateExp_1 = this.generateExp(x.getRight());
    _builder.append(_generateExp_1);
    _builder.append(")");
    return _builder;
  }
  
  public String generateOp(final RelationalOp op) {
    String _switchResult = null;
    boolean _matched = false;
    if (op instanceof RelEQ) {
      _matched=true;
      _switchResult = "==";
    }
    if (!_matched) {
      if (op instanceof RelLT) {
        _matched=true;
        _switchResult = "<";
      }
    }
    if (!_matched) {
      if (op instanceof RelGT) {
        _matched=true;
        _switchResult = ">";
      }
    }
    if (!_matched) {
      if (op instanceof RelLTE) {
        _matched=true;
        _switchResult = "<=";
      }
    }
    if (!_matched) {
      if (op instanceof RelGTE) {
        _matched=true;
        _switchResult = ">=";
      }
    }
    return _switchResult;
  }
  
  protected CharSequence _generateExp(final Add x) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("(");
    CharSequence _generateExp = this.generateExp(x.getLeft());
    _builder.append(_generateExp);
    _builder.append("+");
    CharSequence _generateExp_1 = this.generateExp(x.getRight());
    _builder.append(_generateExp_1);
    _builder.append(")");
    return _builder;
  }
  
  protected CharSequence _generateExp(final Sub x) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("(");
    CharSequence _generateExp = this.generateExp(x.getLeft());
    _builder.append(_generateExp);
    _builder.append("-");
    CharSequence _generateExp_1 = this.generateExp(x.getRight());
    _builder.append(_generateExp_1);
    _builder.append(")");
    return _builder;
  }
  
  protected CharSequence _generateExp(final Mul x) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("(");
    CharSequence _generateExp = this.generateExp(x.getLeft());
    _builder.append(_generateExp);
    _builder.append("*");
    CharSequence _generateExp_1 = this.generateExp(x.getRight());
    _builder.append(_generateExp_1);
    _builder.append(")");
    return _builder;
  }
  
  protected CharSequence _generateExp(final Div x) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("(");
    CharSequence _generateExp = this.generateExp(x.getLeft());
    _builder.append(_generateExp);
    _builder.append("/");
    CharSequence _generateExp_1 = this.generateExp(x.getRight());
    _builder.append(_generateExp_1);
    _builder.append(")");
    return _builder;
  }
  
  protected CharSequence _generateExp(final Name x) {
    return x.getVarName().getName();
  }
  
  protected CharSequence _generateExp(final IntExp x) {
    return Integer.toString(x.getValue());
  }
  
  public void generateExternalInterface(final EntityModel em, final IFileSystemAccess2 fsa) {
    String _name = em.getName();
    String _plus = (_name + "/IExternalCode.cs");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("namespace ");
    String _name_1 = em.getName();
    _builder.append(_name_1);
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("public interface IExternalCode {");
    _builder.newLine();
    {
      Iterable<ExternalDef> _filter = Iterables.<ExternalDef>filter(em.getDeclarations(), ExternalDef.class);
      for(final ExternalDef x : _filter) {
        _builder.append("\t\t");
        _builder.append("public bool ");
        String _name_2 = x.getName();
        _builder.append(_name_2, "\t\t");
        _builder.append("(");
        String _name_3 = x.getType().getName();
        _builder.append(_name_3, "\t\t");
        _builder.append(" parameter);");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    fsa.generateFile(_plus, _builder);
  }
  
  public void generateControllerFiles(final EntityModel em, final IFileSystemAccess2 fsa) {
    final Consumer<Controller> _function = (Controller it) -> {
      this.generateController(it, fsa);
    };
    Iterables.<Controller>filter(em.getDeclarations(), Controller.class).forEach(_function);
  }
  
  public void generateController(final Controller controller, final IFileSystemAccess2 fsa) {
    final EntityModel model = EcoreUtil2.<EntityModel>getContainerOfType(controller, EntityModel.class);
    String _name = model.getName();
    String _plus = (_name + "/Controllers/");
    String _name_1 = controller.getName();
    String _plus_1 = (_plus + _name_1);
    String _plus_2 = (_plus_1 + ".cs");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("using EmTest.Models;");
    _builder.newLine();
    _builder.append("using EmTest.Application.Interfaces;");
    _builder.newLine();
    _builder.append("using EmTest.Application.Parameters;");
    _builder.newLine();
    _builder.append("using Microsoft.AspNetCore.Http;");
    _builder.newLine();
    _builder.append("using Microsoft.AspNetCore.Mvc;");
    _builder.newLine();
    _builder.append("using System.Collections.Generic;");
    _builder.newLine();
    _builder.append("using System.Net;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("namespace ");
    String _name_2 = model.getName();
    _builder.append(_name_2);
    _builder.append(".Controllers {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("[Route(\"api/[controller]\")]");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("[Produces(\"application/json\")]");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("[Consumes(\"application/json\")]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public class ");
    String _name_3 = controller.getName();
    _builder.append(_name_3, "\t");
    _builder.append(" : ControllerBase {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    CharSequence _generateControllerConstructor = this.generateControllerConstructor(controller);
    _builder.append(_generateControllerConstructor, "\t\t");
    _builder.newLineIfNotEmpty();
    {
      EList<ControllerMethod> _methods = controller.getMethods();
      for(final ControllerMethod x : _methods) {
        _builder.append("\t\t");
        CharSequence _generateControllerMethod = this.generateControllerMethod(x, controller.getEntity());
        _builder.append(_generateControllerMethod, "\t\t");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    fsa.generateFile(_plus_2, _builder);
  }
  
  public CharSequence generateControllerConstructor(final Controller controller) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("private readonly I");
    String _name = controller.getEntity().getName();
    _builder.append(_name);
    _builder.append("Service Service;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public ");
    String _name_1 = controller.getName();
    _builder.append(_name_1);
    _builder.append("(I");
    String _name_2 = controller.getEntity().getName();
    _builder.append(_name_2);
    _builder.append("Service service)");
    _builder.newLineIfNotEmpty();
    _builder.append("{");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Service = service;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _generateControllerMethod(final CreateMethod method, final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("[HttpPost]");
    _builder.newLine();
    _builder.append("[ProducesResponseType(StatusCodes.Status201Created)]");
    _builder.newLine();
    _builder.append("public ActionResult<");
    String _name = entity.getName();
    _builder.append(_name);
    _builder.append("> Create(Create");
    String _name_1 = entity.getName();
    _builder.append(_name_1);
    _builder.append("Parameters parameters)");
    _builder.newLineIfNotEmpty();
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("return Created(\"\", Service.Create(parameters));");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _generateControllerMethod(final GetMethod method, final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("[HttpGet(\"{");
    String _firstLower = StringExtensions.toFirstLower(method.getEntityId().getName());
    _builder.append(_firstLower);
    _builder.append("}\")]");
    _builder.newLineIfNotEmpty();
    _builder.append("[ProducesResponseType(typeof(");
    String _name = entity.getName();
    _builder.append(_name);
    _builder.append("), (int) HttpStatusCode.OK)]");
    _builder.newLineIfNotEmpty();
    _builder.append("public ActionResult<");
    String _name_1 = entity.getName();
    _builder.append(_name_1);
    _builder.append("> Get(");
    String _name_2 = method.getEntityId().getType().getName();
    _builder.append(_name_2);
    _builder.append(" ");
    String _firstLower_1 = StringExtensions.toFirstLower(method.getEntityId().getName());
    _builder.append(_firstLower_1);
    _builder.append(")");
    _builder.newLineIfNotEmpty();
    _builder.append("{");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return Ok(Service.Get(new Get");
    String _name_3 = entity.getName();
    _builder.append(_name_3, "    ");
    _builder.append("Parameters");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("    \t");
    String _name_4 = method.getEntityId().getName();
    _builder.append(_name_4, "    \t");
    _builder.append(" = ");
    String _firstLower_2 = StringExtensions.toFirstLower(method.getEntityId().getName());
    _builder.append(_firstLower_2, "    \t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}));");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _generateControllerMethod(final ListMethod method, final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("[HttpGet]");
    _builder.newLine();
    _builder.append("[ProducesResponseType(typeof(");
    String _name = entity.getName();
    _builder.append(_name);
    _builder.append("[]), (int) HttpStatusCode.OK)]");
    _builder.newLineIfNotEmpty();
    _builder.append("public ActionResult<IList<");
    String _name_1 = entity.getName();
    _builder.append(_name_1);
    _builder.append(">> List()");
    _builder.newLineIfNotEmpty();
    _builder.append("{");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return Ok(Service.List(new List");
    String _name_2 = entity.getName();
    _builder.append(_name_2, "    ");
    _builder.append("Parameters()));");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _generateControllerMethod(final UpdateMethod method, final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("[HttpPut(\"{");
    String _firstLower = StringExtensions.toFirstLower(method.getEntityId().getName());
    _builder.append(_firstLower);
    _builder.append("}\")]");
    _builder.newLineIfNotEmpty();
    _builder.append("[ProducesResponseType(typeof(");
    String _name = entity.getName();
    _builder.append(_name);
    _builder.append("), (int) HttpStatusCode.OK)]");
    _builder.newLineIfNotEmpty();
    _builder.append("public ActionResult<");
    String _name_1 = entity.getName();
    _builder.append(_name_1);
    _builder.append("> Update(");
    String _name_2 = method.getEntityId().getType().getName();
    _builder.append(_name_2);
    _builder.append(" ");
    String _firstLower_1 = StringExtensions.toFirstLower(method.getEntityId().getName());
    _builder.append(_firstLower_1);
    _builder.append(", Update");
    String _name_3 = entity.getName();
    _builder.append(_name_3);
    _builder.append("Parameters parameters)");
    _builder.newLineIfNotEmpty();
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("return Ok(Service.Update(new Update");
    String _name_4 = entity.getName();
    _builder.append(_name_4, "\t");
    _builder.append("ParametersWithId");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t");
    String _name_5 = method.getEntityId().getName();
    _builder.append(_name_5, "\t\t");
    _builder.append(" = ");
    String _firstLower_2 = StringExtensions.toFirstLower(method.getEntityId().getName());
    _builder.append(_firstLower_2, "\t\t");
    _builder.append(",");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("Parameters = parameters");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}));");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _generateControllerMethod(final DeleteMethod method, final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("[HttpDelete(\"{");
    String _firstLower = StringExtensions.toFirstLower(method.getEntityId().getName());
    _builder.append(_firstLower);
    _builder.append("}\")]");
    _builder.newLineIfNotEmpty();
    _builder.append("[ProducesResponseType((int) HttpStatusCode.OK)]");
    _builder.newLine();
    _builder.append("public ActionResult Delete(");
    String _name = method.getEntityId().getType().getName();
    _builder.append(_name);
    _builder.append(" ");
    String _firstLower_1 = StringExtensions.toFirstLower(method.getEntityId().getName());
    _builder.append(_firstLower_1);
    _builder.append(")");
    _builder.newLineIfNotEmpty();
    _builder.append("{");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return Ok(Service.Delete(new Delete");
    String _name_1 = entity.getName();
    _builder.append(_name_1, "    ");
    _builder.append("Parameters");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("    \t");
    String _name_2 = method.getEntityId().getName();
    _builder.append(_name_2, "    \t");
    _builder.append(" = ");
    String _firstLower_2 = StringExtensions.toFirstLower(method.getEntityId().getName());
    _builder.append(_firstLower_2, "    \t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}));");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public void generateEntityApplicationInterfaces(final EntityModel em, final IFileSystemAccess2 fsa) {
    final Consumer<Entity> _function = (Entity it) -> {
      this.generateEntityApplicationInterface(it, fsa);
    };
    Iterables.<Entity>filter(em.getDeclarations(), Entity.class).forEach(_function);
    final Consumer<Entity> _function_1 = (Entity it) -> {
      this.generateEntityApplicationParameters(it, fsa);
    };
    Iterables.<Entity>filter(em.getDeclarations(), Entity.class).forEach(_function_1);
  }
  
  public void generateEntityApplicationInterface(final Entity entity, final IFileSystemAccess2 fsa) {
    final EntityModel model = EcoreUtil2.<EntityModel>getContainerOfType(entity, EntityModel.class);
    final Function1<Controller, Boolean> _function = (Controller c) -> {
      Entity _entity = c.getEntity();
      return Boolean.valueOf((_entity == entity));
    };
    final Controller controller = IterableExtensions.<Controller>findFirst(Iterables.<Controller>filter(model.getDeclarations(), Controller.class), _function);
    if ((controller == null)) {
      return;
    }
    String _name = model.getName();
    String _plus = (_name + "/Application/Interfaces/I");
    String _name_1 = entity.getName();
    String _plus_1 = (_plus + _name_1);
    String _plus_2 = (_plus_1 + "Service.cs");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("using System.Collections.Generic;");
    _builder.newLine();
    _builder.append("using EmTest.Application.Parameters;");
    _builder.newLine();
    _builder.append("using EmTest.Models;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("namespace ");
    String _name_2 = model.getName();
    _builder.append(_name_2);
    _builder.append(".Application.Interfaces {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("public interface I");
    String _name_3 = entity.getName();
    _builder.append(_name_3, "\t");
    _builder.append("Service {");
    _builder.newLineIfNotEmpty();
    {
      EList<ControllerMethod> _methods = controller.getMethods();
      for(final ControllerMethod x : _methods) {
        _builder.append("\t\t");
        CharSequence _generateServiceMethod = this.generateServiceMethod(x, entity);
        _builder.append(_generateServiceMethod, "\t\t");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    fsa.generateFile(_plus_2, _builder);
  }
  
  protected CharSequence _generateServiceMethod(final CreateMethod method, final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public ");
    String _name = entity.getName();
    _builder.append(_name);
    _builder.append(" Create(Create");
    String _name_1 = entity.getName();
    _builder.append(_name_1);
    _builder.append("Parameters parameters);");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateServiceMethod(final GetMethod method, final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public ");
    String _name = entity.getName();
    _builder.append(_name);
    _builder.append(" Get(Get");
    String _name_1 = entity.getName();
    _builder.append(_name_1);
    _builder.append("Parameters parameters);");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateServiceMethod(final ListMethod method, final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public IList<");
    String _name = entity.getName();
    _builder.append(_name);
    _builder.append("> List(List");
    String _name_1 = entity.getName();
    _builder.append(_name_1);
    _builder.append("Parameters parameters);");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateServiceMethod(final UpdateMethod method, final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public ");
    String _name = entity.getName();
    _builder.append(_name);
    _builder.append(" Update(Update");
    String _name_1 = entity.getName();
    _builder.append(_name_1);
    _builder.append("ParametersWithId parameters);");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateServiceMethod(final DeleteMethod method, final Entity entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public void Delete(Delete");
    String _name = entity.getName();
    _builder.append(_name);
    _builder.append("Parameters parameters);");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public void generateEntityApplicationParameters(final Entity entity, final IFileSystemAccess2 fsa) {
    final EntityModel model = EcoreUtil2.<EntityModel>getContainerOfType(entity, EntityModel.class);
    final Function1<Controller, Boolean> _function = (Controller c) -> {
      Entity _entity = c.getEntity();
      return Boolean.valueOf((_entity == entity));
    };
    final Controller controller = IterableExtensions.<Controller>findFirst(Iterables.<Controller>filter(model.getDeclarations(), Controller.class), _function);
    if ((controller == null)) {
      return;
    }
    final Consumer<ControllerMethod> _function_1 = (ControllerMethod it) -> {
      this.generateControllerParameters(it, entity, fsa);
    };
    controller.getMethods().forEach(_function_1);
  }
  
  protected void _generateControllerParameters(final CreateMethod method, final Entity entity, final IFileSystemAccess2 fsa) {
    final EntityModel model = EcoreUtil2.<EntityModel>getContainerOfType(entity, EntityModel.class);
    String _name = model.getName();
    String _plus = (_name + "/Application/Parameters/Create");
    String _name_1 = entity.getName();
    String _plus_1 = (_plus + _name_1);
    String _plus_2 = (_plus_1 + "Parameters.cs");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("namespace ");
    String _name_2 = model.getName();
    _builder.append(_name_2);
    _builder.append(".Application.Parameters {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("public class Create");
    String _name_3 = entity.getName();
    _builder.append(_name_3, "\t");
    _builder.append("Parameters {");
    _builder.newLineIfNotEmpty();
    {
      ArrayList<Attribute> _allAttributes = this.getAllAttributes(entity);
      for(final Attribute x : _allAttributes) {
        {
          boolean _contains = method.getExclude().getAttributes().contains(x);
          boolean _not = (!_contains);
          if (_not) {
            _builder.append("\t\t");
            _builder.append("public ");
            String _name_4 = x.getType().getName();
            _builder.append(_name_4, "\t\t");
            _builder.append(" ");
            String _name_5 = x.getName();
            _builder.append(_name_5, "\t\t");
            _builder.append(" { get; set; }");
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    fsa.generateFile(_plus_2, _builder);
  }
  
  protected void _generateControllerParameters(final GetMethod method, final Entity entity, final IFileSystemAccess2 fsa) {
    final EntityModel model = EcoreUtil2.<EntityModel>getContainerOfType(entity, EntityModel.class);
    String _name = model.getName();
    String _plus = (_name + "/Application/Parameters/Get");
    String _name_1 = entity.getName();
    String _plus_1 = (_plus + _name_1);
    String _plus_2 = (_plus_1 + "Parameters.cs");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("namespace ");
    String _name_2 = model.getName();
    _builder.append(_name_2);
    _builder.append(".Application.Parameters {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("public class Get");
    String _name_3 = entity.getName();
    _builder.append(_name_3, "\t");
    _builder.append("Parameters {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("public ");
    String _name_4 = method.getEntityId().getType().getName();
    _builder.append(_name_4, "\t\t");
    _builder.append(" ");
    String _name_5 = method.getEntityId().getName();
    _builder.append(_name_5, "\t\t");
    _builder.append(" { get; set; }");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    fsa.generateFile(_plus_2, _builder);
  }
  
  protected void _generateControllerParameters(final ListMethod method, final Entity entity, final IFileSystemAccess2 fsa) {
    final EntityModel model = EcoreUtil2.<EntityModel>getContainerOfType(entity, EntityModel.class);
    String _name = model.getName();
    String _plus = (_name + "/Application/Parameters/List");
    String _name_1 = entity.getName();
    String _plus_1 = (_plus + _name_1);
    String _plus_2 = (_plus_1 + "Parameters.cs");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("namespace ");
    String _name_2 = model.getName();
    _builder.append(_name_2);
    _builder.append(".Application.Parameters {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("public class List");
    String _name_3 = entity.getName();
    _builder.append(_name_3, "\t");
    _builder.append("Parameters {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    fsa.generateFile(_plus_2, _builder);
  }
  
  protected void _generateControllerParameters(final UpdateMethod method, final Entity entity, final IFileSystemAccess2 fsa) {
    final EntityModel model = EcoreUtil2.<EntityModel>getContainerOfType(entity, EntityModel.class);
    String _name = model.getName();
    String _plus = (_name + "/Application/Parameters/Update");
    String _name_1 = entity.getName();
    String _plus_1 = (_plus + _name_1);
    String _plus_2 = (_plus_1 + "Parameters.cs");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("namespace ");
    String _name_2 = model.getName();
    _builder.append(_name_2);
    _builder.append(".Application.Parameters {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("public class Update");
    String _name_3 = entity.getName();
    _builder.append(_name_3, "\t");
    _builder.append("ParametersWithId {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("public ");
    String _name_4 = method.getEntityId().getType().getName();
    _builder.append(_name_4, "\t\t");
    _builder.append(" ");
    String _name_5 = method.getEntityId().getName();
    _builder.append(_name_5, "\t\t");
    _builder.append(" { get; set; }");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("public Update");
    String _name_6 = entity.getName();
    _builder.append(_name_6, "\t\t");
    _builder.append("Parameters Parameters { get; set; }");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public class Update");
    String _name_7 = entity.getName();
    _builder.append(_name_7, "\t");
    _builder.append("Parameters {");
    _builder.newLineIfNotEmpty();
    {
      Iterable<Attribute> _filter = Iterables.<Attribute>filter(entity.getDeclarations(), Attribute.class);
      for(final Attribute x : _filter) {
        {
          Attribute _entityId = method.getEntityId();
          boolean _tripleNotEquals = (x != _entityId);
          if (_tripleNotEquals) {
            _builder.append("\t\t");
            _builder.append("public ");
            String _name_8 = x.getType().getName();
            _builder.append(_name_8, "\t\t");
            _builder.append(" ");
            String _name_9 = x.getName();
            _builder.append(_name_9, "\t\t");
            _builder.append(" { get; set; }");
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    fsa.generateFile(_plus_2, _builder);
  }
  
  protected void _generateControllerParameters(final DeleteMethod method, final Entity entity, final IFileSystemAccess2 fsa) {
    final EntityModel model = EcoreUtil2.<EntityModel>getContainerOfType(entity, EntityModel.class);
    String _name = model.getName();
    String _plus = (_name + "/Application/Parameters/Delete");
    String _name_1 = entity.getName();
    String _plus_1 = (_plus + _name_1);
    String _plus_2 = (_plus_1 + "Parameters.cs");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("namespace ");
    String _name_2 = model.getName();
    _builder.append(_name_2);
    _builder.append(".Application.Parameters {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("public class Delete");
    String _name_3 = entity.getName();
    _builder.append(_name_3, "\t");
    _builder.append("Parameters {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("public ");
    String _name_4 = method.getEntityId().getType().getName();
    _builder.append(_name_4, "\t\t");
    _builder.append(" ");
    String _name_5 = method.getEntityId().getName();
    _builder.append(_name_5, "\t\t");
    _builder.append(" { get; set; }");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    fsa.generateFile(_plus_2, _builder);
  }
  
  public ArrayList<Attribute> getAllAttributes(final Entity entity) {
    final ArrayList<Attribute> attributes = new ArrayList<Attribute>();
    Entity currentBase = entity;
    while ((currentBase != null)) {
      {
        Iterables.<Attribute>addAll(attributes, Iterables.<Attribute>filter(currentBase.getDeclarations(), Attribute.class));
        currentBase = currentBase.getBase();
      }
    }
    return attributes;
  }
  
  public static ArrayList<Attribute> getAllAttributesStatic(final Entity entity) {
    return new RestControllerGenerationGenerator().getAllAttributes(entity);
  }
  
  public CharSequence generateAttributeRequirement(final EObject requirement, final Attribute attribute) {
    if (requirement instanceof ExternalUse) {
      return _generateAttributeRequirement((ExternalUse)requirement, attribute);
    } else if (requirement instanceof LogicRequirement) {
      return _generateAttributeRequirement((LogicRequirement)requirement, attribute);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(requirement, attribute).toString());
    }
  }
  
  public CharSequence generateRequirement(final EObject requirement) {
    if (requirement instanceof ExternalUseOfAttribute) {
      return _generateRequirement((ExternalUseOfAttribute)requirement);
    } else if (requirement instanceof LogicRequirement) {
      return _generateRequirement((LogicRequirement)requirement);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(requirement).toString());
    }
  }
  
  public CharSequence generateLogic(final Proposition x) {
    if (x instanceof Comparison) {
      return _generateLogic((Comparison)x);
    } else if (x instanceof Conjunction) {
      return _generateLogic((Conjunction)x);
    } else if (x instanceof Disjunction) {
      return _generateLogic((Disjunction)x);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(x).toString());
    }
  }
  
  public CharSequence generateExp(final Expression x) {
    if (x instanceof Add) {
      return _generateExp((Add)x);
    } else if (x instanceof Div) {
      return _generateExp((Div)x);
    } else if (x instanceof IntExp) {
      return _generateExp((IntExp)x);
    } else if (x instanceof Mul) {
      return _generateExp((Mul)x);
    } else if (x instanceof Name) {
      return _generateExp((Name)x);
    } else if (x instanceof Sub) {
      return _generateExp((Sub)x);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(x).toString());
    }
  }
  
  public CharSequence generateControllerMethod(final ControllerMethod method, final Entity entity) {
    if (method instanceof CreateMethod) {
      return _generateControllerMethod((CreateMethod)method, entity);
    } else if (method instanceof DeleteMethod) {
      return _generateControllerMethod((DeleteMethod)method, entity);
    } else if (method instanceof GetMethod) {
      return _generateControllerMethod((GetMethod)method, entity);
    } else if (method instanceof ListMethod) {
      return _generateControllerMethod((ListMethod)method, entity);
    } else if (method instanceof UpdateMethod) {
      return _generateControllerMethod((UpdateMethod)method, entity);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(method, entity).toString());
    }
  }
  
  public CharSequence generateServiceMethod(final ControllerMethod method, final Entity entity) {
    if (method instanceof CreateMethod) {
      return _generateServiceMethod((CreateMethod)method, entity);
    } else if (method instanceof DeleteMethod) {
      return _generateServiceMethod((DeleteMethod)method, entity);
    } else if (method instanceof GetMethod) {
      return _generateServiceMethod((GetMethod)method, entity);
    } else if (method instanceof ListMethod) {
      return _generateServiceMethod((ListMethod)method, entity);
    } else if (method instanceof UpdateMethod) {
      return _generateServiceMethod((UpdateMethod)method, entity);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(method, entity).toString());
    }
  }
  
  public void generateControllerParameters(final ControllerMethod method, final Entity entity, final IFileSystemAccess2 fsa) {
    if (method instanceof CreateMethod) {
      _generateControllerParameters((CreateMethod)method, entity, fsa);
      return;
    } else if (method instanceof DeleteMethod) {
      _generateControllerParameters((DeleteMethod)method, entity, fsa);
      return;
    } else if (method instanceof GetMethod) {
      _generateControllerParameters((GetMethod)method, entity, fsa);
      return;
    } else if (method instanceof ListMethod) {
      _generateControllerParameters((ListMethod)method, entity, fsa);
      return;
    } else if (method instanceof UpdateMethod) {
      _generateControllerParameters((UpdateMethod)method, entity, fsa);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(method, entity, fsa).toString());
    }
  }
}
